name: Deploy to S3

on:
  workflow_run:
    workflows: ["CI Pipeline with GHCR"]
    types: [completed]
    branches: [main]

env:
  AWS_REGION: 'ap-southeast-2'                 
  S3_BUCKET: 'weather-web-sabrina1705'     
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install and build React app
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Deploy to S3
        run: |
          # Sync all files (except cached HTML)
          aws s3 sync ./frontend/build s3://${{ env.S3_BUCKET }} --delete
          
          # Force no-cache for index.html
          aws s3 cp ./frontend/build/index.html s3://${{ env.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --metadata-directive REPLACE

